#!/usr/bin/env python3
# -'''- coding: utf-8 -'''-

import sys
import time

from ApplicationControlWidget import ApplicationControlWidget
from ApplicationStatusWidget import ApplicationStatusWidget
from ApplicationPaginationWidget import ApplicationPaginationWidget

from ActuatorOverviewPageWidget import ActuatorOverviewPageWidget
from AirPageWidget import AirPageWidget
from CellLightPageWidget import CellLightPageWidget
from DCAccelerometerPageWidget import DCAccelerometerPageWidget
from ForceActuatorGraphPageWidget import ForceActuatorGraphPageWidget
from ForceActuatorValuePageWidget import ForceActuatorValuePageWidget
from ForceBalanceSystemPageWidget import ForceBalanceSystemPageWidget
from ForceActuatorBumpTestPageWidget import ForceActuatorBumpTestPageWidget
from GyroPageWidget import GyroPageWidget
from HardpointsWidget import HardpointsWidget
from IMSPageWidget import IMSPageWidget
from InclinometerPageWidget import InclinometerPageWidget
from InterlockPageWidget import InterlockPageWidget
from OverviewPageWidget import OverviewPageWidget
from PIDPageWidget import PIDPageWidget
from PositionWidget import PositionWidget
from PowerPageWidget import PowerPageWidget
from SALLogWidget import SALLogWidget

import SALComm

from PySide2.QtWidgets import QApplication, QVBoxLayout, QDialog, QHBoxLayout, QLabel
from PySide2.QtGui import QFont

from asyncqt import QEventLoop, asyncClose
import asyncio


class EUI(QDialog):
    def __init__(self, loop, parent=None):
        super(EUI, self).__init__(parent)
        self.layout = QVBoxLayout()
        self.topLayerLayout = QHBoxLayout()

        self.comm = SALComm.create(
            {"MTM1M3": None, "MTMount": ["azimuth", "elevation"]}
        )

        self.applicationControlLayout = QVBoxLayout()
        self.applicationControl = ApplicationControlWidget(self.comm)
        self.applicationControl.setFixedSize(256, 175)
        self.applicationControlLayout.addWidget(QLabel("Application Control"))
        self.applicationControlLayout.addWidget(self.applicationControl)
        self.topLayerLayout.addLayout(self.applicationControlLayout)

        self.applicationStatusLayout = QVBoxLayout()
        self.applicationStatus = ApplicationStatusWidget(self.comm)
        self.applicationStatus.setFixedHeight(175)
        self.applicationStatusLayout.addWidget(QLabel("Application Status"))
        self.applicationStatusLayout.addWidget(self.applicationStatus)
        self.topLayerLayout.addLayout(self.applicationStatusLayout)

        self.middleLayerLayout = QHBoxLayout()
        self.applicationPagination = ApplicationPaginationWidget()
        self.applicationPagination.setPageListWidth(238)

        self.addPage("Overview", OverviewPageWidget(self.comm))
        self.addPage("Actuator Overview", ActuatorOverviewPageWidget(self.comm))
        self.addPage("Hardpoints", HardpointsWidget(self.comm))
        self.addPage("Position", PositionWidget(self.comm))
        self.addPage("DC Accelerometers", DCAccelerometerPageWidget(self.comm))
        self.addPage("Gyro", GyroPageWidget(self.comm))
        self.addPage("IMS", IMSPageWidget(self.comm))
        self.addPage("Inclinometer", InclinometerPageWidget(self.comm))
        self.addPage("Interlock", InterlockPageWidget(self.comm))
        self.addPage("Lights", CellLightPageWidget(self.comm))
        self.addPage("Air", AirPageWidget(self.comm))
        self.addPage("Power", PowerPageWidget(self.comm))
        self.addPage("PID", PIDPageWidget(self.comm))
        self.addPage("Force Balance System", ForceBalanceSystemPageWidget(self.comm))
        self.addPage(
            "Force Actuator Bump Test", ForceActuatorBumpTestPageWidget(self.comm)
        )
        self.addPage("Force Actuator Graph", ForceActuatorGraphPageWidget(self.comm))
        self.addPage("Force Actuator Value", ForceActuatorValuePageWidget(self.comm))
        self.addPage("SAL Log", SALLogWidget(self.comm))
        self.middleLayerLayout.addWidget(self.applicationPagination)
        self.bottomLayerLayout = QHBoxLayout()
        self.layout.addLayout(self.topLayerLayout)
        self.layout.addLayout(self.middleLayerLayout)
        self.layout.addLayout(self.bottomLayerLayout)
        self.setLayout(self.layout)
        self.setFixedSize(1900, 1000)

    def addPage(self, name, widget):
        self.applicationPagination.addPage(name, widget)

    @asyncClose
    async def closeEvent(self, event):
        await self.comm.close()


if __name__ == "__main__":
    # Create the Qt Application
    app = QApplication(sys.argv)
    loop = QEventLoop(app)
    asyncio.set_event_loop(loop)

    # Create EUI
    eui = EUI(loop)
    eui.show()

    # Run the main Qt loop
    with loop:
        loop.run_forever()

    # Close application
    sys.exit()
